import os
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from dotenv import load_dotenv

load_dotenv()

class EmailDraft:
    def __init__(self, recipient="amaankamil7@gmail.com"):
        self.recipient = recipient
        self.sender_email = os.getenv("EMAIL_USER")
        self.sender_password = os.getenv("EMAIL_PASSWORD")

    def create_draft(self, subject, body):
        """Formats the email draft."""
        email_content = f"""To: {self.recipient}
Subject: {subject}

{body}

---
This is an automated weekly report.
"""
        return email_content

    def save_draft(self, content, filename="email_draft.txt"):
        """Saves the draft to a file."""
        try:
            with open(filename, "w") as f:
                f.write(content)
            return os.path.abspath(filename)
        except Exception as e:
            print(f"Error saving draft: {e}")
            return None

    def send_email(self, subject, body, image_paths=None, dashboard_url="http://localhost:8501"):
        """Sends the email using SMTP with HTML formatting and inline images."""
        if not self.sender_email or not self.sender_password:
            print("ERROR: Email credentials not found in .env. Skipping email send.")
            return False

        try:
            import markdown
            from email.mime.image import MIMEImage

            # Clean up markdown artifacts
            clean_body = body.replace("```markdown", "").replace("```", "").strip()
            
            # Convert Markdown to HTML
            html_body = markdown.markdown(clean_body)
            
            # Prepare image HTML
            images_html = ""
            if image_paths:
                images_html = "<h3>Visual Insights</h3>"
                for i, _ in enumerate(image_paths):
                    images_html += f'<div style="margin-bottom: 20px;"><img src="cid:image{i}" style="max-width: 100%; height: auto; border: 1px solid #ddd; border-radius: 5px;"></div>'

            # Add styling and structure
            styled_html = f"""
            <html>
            <head>
                <style>
                    body {{ font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; line-height: 1.6; color: #333; background-color: #f9f9f9; padding: 20px; }}
                    .container {{ max-width: 600px; margin: 0 auto; background: #ffffff; padding: 30px; border-radius: 8px; box-shadow: 0 2px 5px rgba(0,0,0,0.05); }}
                    h1 {{ color: #2c3e50; font-size: 24px; margin-bottom: 20px; border-bottom: 2px solid #eee; padding-bottom: 10px; }}
                    h2 {{ color: #34495e; font-size: 20px; margin-top: 25px; }}
                    h3 {{ color: #7f8c8d; font-size: 16px; text-transform: uppercase; letter-spacing: 1px; margin-top: 20px; }}
                    ul {{ padding-left: 20px; }}
                    li {{ margin-bottom: 10px; }}
                    strong {{ color: #2980b9; }}
                    .button {{ display: inline-block; padding: 12px 24px; background-color: #00d09c; color: white; text-decoration: none; border-radius: 5px; font-weight: bold; margin-top: 20px; }}
                    .footer {{ margin-top: 30px; font-size: 12px; color: #95a5a6; text-align: center; border-top: 1px solid #eee; padding-top: 20px; }}
                </style>
            </head>
            <body>
                <div class="container">
                    {html_body}
                    
                    {images_html}
                    
                    <div style="text-align: center;">
                        <a href="{dashboard_url}" class="button">View Full Dashboard</a>
                    </div>

                    <div class="footer">
                        <p>This is an automated weekly report generated by App Review Insights Analyzer.</p>
                        <p>&copy; 2025 Groww Analytics Team</p>
                    </div>
                </div>
            </body>
            </html>
            """

            msg = MIMEMultipart('related')
            msg['From'] = self.sender_email
            msg['To'] = self.recipient
            msg['Subject'] = subject

            msg_alternative = MIMEMultipart('alternative')
            msg.attach(msg_alternative)

            part1 = MIMEText(clean_body, 'plain')
            part2 = MIMEText(styled_html, 'html')

            msg_alternative.attach(part1)
            msg_alternative.attach(part2)

            # Attach images
            if image_paths:
                for i, path in enumerate(image_paths):
                    try:
                        with open(path, 'rb') as f:
                            img_data = f.read()
                        img = MIMEImage(img_data)
                        img.add_header('Content-ID', f'<image{i}>')
                        img.add_header('Content-Disposition', 'inline', filename=os.path.basename(path))
                        msg.attach(img)
                    except Exception as e:
                        print(f"Failed to attach image {path}: {e}")

            # Connect to Gmail's SMTP server
            with smtplib.SMTP('smtp.gmail.com', 587) as server:
                server.starttls()
                server.login(self.sender_email, self.sender_password)
                server.send_message(msg)
            
            print(f"Email sent successfully to {self.recipient}")
            return True
        except smtplib.SMTPAuthenticationError:
            print("ERROR: Authentication failed. Check your EMAIL_USER and EMAIL_PASSWORD.")
            return False
        except Exception as e:
            print(f"Failed to send email: {e}")
            return False
