import os
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from dotenv import load_dotenv

load_dotenv()

class EmailDraft:
    def __init__(self, recipient="amaankamil7@gmail.com"):
        self.recipient = recipient
        self.sender_email = os.getenv("EMAIL_USER")
        self.sender_password = os.getenv("EMAIL_PASSWORD")

    def create_draft(self, subject, body):
        """Formats the email draft."""
        email_content = f"""To: {self.recipient}
Subject: {subject}

{body}

---
This is an automated weekly report.
"""
        return email_content

    def save_draft(self, content, filename="email_draft.txt"):
        """Saves the draft to a file."""
        try:
            with open(filename, "w") as f:
                f.write(content)
            return os.path.abspath(filename)
        except Exception as e:
            print(f"Error saving draft: {e}")
            return None

    def send_email(self, subject, body):
        """Sends the email using SMTP with HTML formatting."""
        if not self.sender_email or not self.sender_password:
            print("ERROR: Email credentials not found in .env. Skipping email send.")
            return False

        try:
            import markdown
            
            # Convert Markdown to HTML
            html_body = markdown.markdown(body)
            
            # Add some basic styling
            styled_html = f"""
            <html>
            <head>
                <style>
                    body {{ font-family: Arial, sans-serif; line-height: 1.6; color: #333; }}
                    h1, h2, h3 {{ color: #2c3e50; }}
                    ul {{ padding-left: 20px; }}
                    li {{ margin-bottom: 10px; }}
                    strong {{ color: #2980b9; }}
                    .container {{ max-width: 800px; margin: 0 auto; padding: 20px; }}
                    .footer {{ margin-top: 30px; font-size: 12px; color: #7f8c8d; border-top: 1px solid #eee; padding-top: 10px; }}
                </style>
            </head>
            <body>
                <div class="container">
                    {html_body}
                    <div class="footer">
                        This is an automated weekly report generated by App Review Insights Analyzer.
                    </div>
                </div>
            </body>
            </html>
            """

            msg = MIMEMultipart('alternative')
            msg['From'] = self.sender_email
            msg['To'] = self.recipient
            msg['Subject'] = subject

            # Attach both plain text and HTML versions
            part1 = MIMEText(body, 'plain')
            part2 = MIMEText(styled_html, 'html')

            msg.attach(part1)
            msg.attach(part2)

            # Connect to Gmail's SMTP server
            with smtplib.SMTP('smtp.gmail.com', 587) as server:
                server.starttls()
                server.login(self.sender_email, self.sender_password)
                server.send_message(msg)
            
            print(f"Email sent successfully to {self.recipient}")
            return True
        except smtplib.SMTPAuthenticationError:
            print("ERROR: Authentication failed. Check your EMAIL_USER and EMAIL_PASSWORD.")
            return False
        except Exception as e:
            print(f"Failed to send email: {e}")
            return False
